file(MAKE_DIRECTORY ${GEN_DIR}/dead)

extractBitmaps(TARGET ${GAME_EXECUTABLE} SOURCE ${RES_DIR}/game1.png
	GENERATED_FILE_LIST "TILES_DEAD_LIST"
	DESTINATIONS
	${GEN_DIR}/dead/0.png  219 50 16 14
	${GEN_DIR}/dead/1.png  219 64 16 14
	${GEN_DIR}/dead/2.png  219 78 16 14
	${GEN_DIR}/dead/3.png  219 92 16 14
)

convertTileset(
	TARGET ${GAME_EXECUTABLE} SIZE 16 HEIGHT 14 PALETTE ${GAME_PLT_PATH}
	INTERLEAVED SOURCE ${GEN_DIR}/dead DESTINATION ${GEN_DIR}/dead.png
	TILE_PATHS ${TILES_DEAD_LIST}
)

convertBitmaps(
	INTERLEAVED TARGET ${GAME_EXECUTABLE} PALETTE ${GAME_PLT_PATH}
	MASK_COLOR "#000000"
	SOURCES
		${GEN_DIR}/dead.png
	DESTINATIONS
		${DATA_DIR}/dead.bm
	MASKS
		${DATA_DIR}/dead_mask.bm
)
