file(MAKE_DIRECTORY ${GEN_DIR}/hit)

extractBitmaps(TARGET ${GAME_EXECUTABLE} SOURCE ${RES_DIR}/game1.png
	GENERATED_FILE_LIST "TILES_HIT_LIST"
	DESTINATIONS
	${GEN_DIR}/hit/0.png  203 8 16 13
	${GEN_DIR}/hit/1.png  219 8 16 13
)

convertTileset(
	TARGET ${GAME_EXECUTABLE} SIZE 16 HEIGHT 13 PALETTE ${GAME_PLT_PATH}
	INTERLEAVED SOURCE ${GEN_DIR}/hit DESTINATION ${GEN_DIR}/hit.png
	TILE_PATHS ${TILES_HIT_LIST}
)

convertBitmaps(
	INTERLEAVED TARGET ${GAME_EXECUTABLE} PALETTE ${GAME_PLT_PATH}
	MASK_COLOR "#000000"
	SOURCES
		${GEN_DIR}/hit.png
	DESTINATIONS
		${DATA_DIR}/hit.bm
	MASKS
		${DATA_DIR}/hit_mask.bm
)
